project:
  type: website

website:
  title: "My website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Example analysis.qmd

format:
  html:
    theme: Darkly
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto


